apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: test
spec:
  selector:
    app: manager
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: manager
      containers:
        - name: manager
          image: sampling-manager:latest
          imagePullPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    #resourceNames: ["server"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    #resourceNames: [""]
    verbs: ["get", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-binding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: test
roleRef:
  kind: Role
  name: manager
  apiGroup: rbac.authorization.k8s.io
