apiVersion: v1
kind: ConfigMap
metadata:
  name: server
  namespace: test
data:
  # Note!
  #
  # Each top-level key is a file name
  # when mounting a volume.
  config: |
    name=bob
    age=10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: simple-server:latest
          imagePullPolicy: Never
          args:
            - "--conf"
            - "/etc/config/config"
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: server
